### ISSUE TITLE
Python API doesn't install on Ubuntu server

### ISSUE THREAD

**Issue by barrywark** [physion/ovation-webapi#189]
From Hareesh:

```
>>> import ovation
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/WORK/Dev/Ovation/ovation.py", line 6, in <module>
    from ovation.connection import connect
ImportError: No module named 'ovation.connection'; 'ovation' is not a package
>>> exit()
```

**Comment by barrywark** [comment]
http://stackoverflow.com/questions/30261860/python-3-attributeerror-module-object-has-no-attribute-path-using-urll
